/**
 * Generate packages/website/src/data/mcp-tools.ts from the eval tool lists and
 * mcp-tool-catalog.ts. Run via `pnpm gen:mcp-tools` (also runs before build).
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  ATHLETE_READ_TOOLS,
  ATHLETE_WRITE_TOOLS,
  COACH_READ_TOOLS,
  COACH_WRITE_TOOLS,
} from "../../eval/src/tools.ts";
import {
  ATHLETE_GROUP_NAMES,
  COACH_GROUP_NAMES,
  HOSTED_ONLY_TOOL_NAMES,
  TOOL_SUMMARIES,
} from "../src/data/mcp-tool-catalog.ts";

const scriptDir = import.meta.dirname;
const outPath = join(scriptDir, "../src/data/mcp-tools.ts");

function unique<T>(items: readonly T[]): T[] {
  return [...new Set(items)];
}

function assertSetMatches(
  label: string,
  expected: readonly string[],
  grouped: { title: string; tools: string[] }[],
): void {
  const fromGroups = grouped.flatMap((g) => g.tools);
  const expectedSet = new Set(expected);
  const groupedSet = new Set(fromGroups);

  const missing = expected.filter((t) => !groupedSet.has(t));
  const extra = fromGroups.filter((t) => !expectedSet.has(t));
  const dupes = fromGroups.filter((t, i) => fromGroups.indexOf(t) !== i);

  const problems: string[] = [];
  if (missing.length > 0) problems.push(`missing from groups: ${missing.join(", ")}`);
  if (extra.length > 0) problems.push(`unknown in groups: ${extra.join(", ")}`);
  if (dupes.length > 0) problems.push(`duplicates in groups: ${unique(dupes).join(", ")}`);
  if (problems.length > 0) {
    throw new Error(`${label} catalog mismatch — ${problems.join("; ")}`);
  }
}

function summary(name: string): string {
  const text = TOOL_SUMMARIES[name];
  if (!text) throw new Error(`Missing TOOL_SUMMARIES entry for "${name}"`);
  return text;
}

function buildGroups(groups: { title: string; tools: string[] }[]) {
  return groups.map((group) => ({
    title: group.title,
    tools: group.tools.map((name) => ({ name, summary: summary(name) })),
  }));
}

const coachTools = unique([...COACH_READ_TOOLS, ...COACH_WRITE_TOOLS]);
const athleteTools = unique([...ATHLETE_READ_TOOLS, ...ATHLETE_WRITE_TOOLS]);

assertSetMatches("coach", coachTools, COACH_GROUP_NAMES);
assertSetMatches("athlete", athleteTools, ATHLETE_GROUP_NAMES);

for (const name of [...coachTools, ...athleteTools, ...HOSTED_ONLY_TOOL_NAMES]) {
  summary(name);
}

const coachGroups = buildGroups(COACH_GROUP_NAMES);
const athleteGroups = buildGroups(ATHLETE_GROUP_NAMES);
const hostedOnly = HOSTED_ONLY_TOOL_NAMES.map((name) => ({
  name,
  summary: summary(name),
}));

const source = `// Generated by scripts/gen-mcp-tools.mts — do not edit by hand.
// Regenerate: pnpm --filter @trainheroic-unofficial/website gen:mcp-tools

export type McpTool = {
  name: string;
  summary: string;
};

export type McpToolGroup = {
  title: string;
  tools: McpTool[];
};

/** Scannable index — names match the MCP server; summaries are one line each. */
export const COACH_TOOL_GROUPS: McpToolGroup[] = ${JSON.stringify(coachGroups, null, 2)};

export const ATHLETE_TOOL_GROUPS: McpToolGroup[] = ${JSON.stringify(athleteGroups, null, 2)};

export const HOSTED_ONLY_TOOLS: McpTool[] = ${JSON.stringify(hostedOnly, null, 2)};
`;

writeFileSync(outPath, source);
execSync(`pnpm exec oxfmt ${outPath}`, { stdio: "inherit", cwd: join(scriptDir, "../../..") });
console.log(`Wrote ${outPath}`);
