/**
 * Generate the Blume MCP tool catalog from the eval tool lists and
 * mcp-tool-catalog.ts. Run via `pnpm gen:mcp-tools` (also runs before build).
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  ATHLETE_READ_TOOLS,
  ATHLETE_WRITE_TOOLS,
  COACH_READ_TOOLS,
  COACH_WRITE_TOOLS,
} from "../../eval/src/tools.ts";
import {
  ATHLETE_GROUP_NAMES,
  COACH_GROUP_NAMES,
  HOSTED_ONLY_TOOL_NAMES,
  TOOL_SUMMARIES,
} from "../src/data/mcp-tool-catalog.ts";

const scriptDir = import.meta.dirname;
const outPath = join(scriptDir, "../src/content/docs/developers/mcp/02-tools.mdx");

function unique<T>(items: readonly T[]): T[] {
  return [...new Set(items)];
}

function assertSetMatches(
  label: string,
  expected: readonly string[],
  grouped: { title: string; tools: string[] }[],
): void {
  const fromGroups = grouped.flatMap((g) => g.tools);
  const expectedSet = new Set(expected);
  const groupedSet = new Set(fromGroups);

  const missing = expected.filter((t) => !groupedSet.has(t));
  const extra = fromGroups.filter((t) => !expectedSet.has(t));
  const dupes = fromGroups.filter((t, i) => fromGroups.indexOf(t) !== i);

  const problems: string[] = [];
  if (missing.length > 0) problems.push(`missing from groups: ${missing.join(", ")}`);
  if (extra.length > 0) problems.push(`unknown in groups: ${extra.join(", ")}`);
  if (dupes.length > 0) problems.push(`duplicates in groups: ${unique(dupes).join(", ")}`);
  if (problems.length > 0) {
    throw new Error(`${label} catalog mismatch — ${problems.join("; ")}`);
  }
}

function summary(name: string): string {
  const text = TOOL_SUMMARIES[name];
  if (!text) throw new Error(`Missing TOOL_SUMMARIES entry for "${name}"`);
  return text;
}

function buildGroups(groups: { title: string; tools: string[] }[]) {
  return groups.map((group) => ({
    title: group.title,
    tools: group.tools.map((name) => ({ name, summary: summary(name) })),
  }));
}

const coachTools = unique([...COACH_READ_TOOLS, ...COACH_WRITE_TOOLS]);
const athleteTools = unique([...ATHLETE_READ_TOOLS, ...ATHLETE_WRITE_TOOLS]);

assertSetMatches("coach", coachTools, COACH_GROUP_NAMES);
assertSetMatches("athlete", athleteTools, ATHLETE_GROUP_NAMES);

for (const name of [...coachTools, ...athleteTools, ...HOSTED_ONLY_TOOL_NAMES]) {
  summary(name);
}

const coachGroups = buildGroups(COACH_GROUP_NAMES);
const athleteGroups = buildGroups(ATHLETE_GROUP_NAMES);
const hostedOnly = HOSTED_ONLY_TOOL_NAMES.map((name) => ({
  name,
  summary: summary(name),
}));

const table = (tools: { name: string; summary: string }[]) =>
  [
    "| Tool | What it does |",
    "| --- | --- |",
    ...tools.map(({ name, summary: description }) => `| \`${name}\` | ${description} |`),
  ].join("\n");

const groups = (items: { title: string; tools: { name: string; summary: string }[] }[]) =>
  items.map(({ title, tools }) => `### ${title}\n\n${table(tools)}`).join("\n\n");

const source = `---
title: Tool catalog
description: Every TrainHeroic MCP tool, grouped by role and task.
sidebar:
  order: 3
---

{/* Generated by scripts/gen-mcp-tools.mts. Do not edit by hand. */}

The model chooses these tools from your request. Your MCP client shows each tool's full input
schema before it runs.

## Coach tools

Available to coach accounts on the main hosted endpoint and from the local coach server.

${groups(coachGroups)}

## Athlete tools

Available to every account on the main hosted endpoint and from both local servers.

${groups(athleteGroups)}

## Hosted-only tools

These use the hosted server's D1 warehouse or feedback service.

${table(hostedOnly)}
`;

writeFileSync(outPath, source);
console.log(`Wrote ${outPath}`);
