import { defineConfig } from "drizzle-kit";

// This config exists ONLY for parity tooling — `drizzle-kit pull` / `check` to confirm that
// src/store/schema.ts still matches the live D1 tables. Migrations are NOT generated by
// drizzle-kit: they stay hand-written under migrations/ and are applied with
// `wrangler d1 migrations apply` (see CLAUDE.md). The d1-http driver needs a Cloudflare
// account id, database id, and an API token with D1 edit rights, supplied via env vars.
export default defineConfig({
  dialect: "sqlite",
  driver: "d1-http",
  schema: "./src/store/schema.ts",
  out: "./drizzle",
  dbCredentials: {
    accountId: process.env.CLOUDFLARE_ACCOUNT_ID ?? "",
    databaseId: process.env.CLOUDFLARE_DATABASE_ID ?? "",
    token: process.env.CLOUDFLARE_D1_TOKEN ?? "",
  },
});
