// Generated by scripts/gen-mcp-tools.mts — do not edit by hand.
// Regenerate: pnpm --filter @trainheroic-unofficial/website gen:mcp-tools

export type McpTool = {
  name: string;
  summary: string;
};

export type McpToolGroup = {
  title: string;
  tools: McpTool[];
};

/** Scannable index — names match the MCP server; summaries are one line each. */
export const COACH_TOOL_GROUPS: McpToolGroup[] = [
  {
    title: "Account & roster",
    tools: [
      {
        name: "whoami",
        summary: "Your coach profile and roles",
      },
      {
        name: "head_coach",
        summary: "Head coach profile for your organization",
      },
      {
        name: "list_athletes",
        summary: "Everyone on your org roster",
      },
      {
        name: "list_teams",
        summary: "Teams you coach",
      },
      {
        name: "get_team",
        summary: "One team with athletes and program",
      },
      {
        name: "list_programs",
        summary: "Standalone coach programs",
      },
      {
        name: "get_program",
        summary: "Program detail by id",
      },
      {
        name: "notifications",
        summary: "Unread notifications",
      },
      {
        name: "analytics_categories",
        summary: "Analytics metric categories",
      },
      {
        name: "roster_activity",
        summary: "Recent training activity across the roster",
      },
      {
        name: "athlete_training",
        summary: "Filterable athlete training history",
      },
      {
        name: "athlete_lift_history",
        summary: "Lift history for one athlete",
      },
      {
        name: "team_volume",
        summary: "Volume totals for a team",
      },
    ],
  },
  {
    title: "Workouts & sessions",
    tools: [
      {
        name: "workout_build",
        summary: "Program a session from blocks",
      },
      {
        name: "workout_read",
        summary: "Read a programmed workout",
      },
      {
        name: "workout_publish",
        summary: "Publish a draft to athletes",
      },
      {
        name: "session_remove",
        summary: "Remove a session from a program",
      },
      {
        name: "session_unpublish",
        summary: "Unpublish a live session",
      },
      {
        name: "session_copy",
        summary: "Copy a session to another date",
      },
      {
        name: "session_save_as_template",
        summary: "Save a session as a template",
      },
    ],
  },
  {
    title: "Exercise library",
    tools: [
      {
        name: "exercise_resolve",
        summary: "Map a name to one exercise id",
      },
      {
        name: "exercise_search",
        summary: "Fuzzy search the library",
      },
      {
        name: "exercise_get",
        summary: "Full exercise by id",
      },
      {
        name: "exercise_sync",
        summary: "Refresh the cached library",
      },
      {
        name: "exercise_create",
        summary: "Create a custom exercise",
      },
      {
        name: "exercise_forget",
        summary: "Remove a custom exercise from the cache",
      },
      {
        name: "store_stats",
        summary: "Library cache stats",
      },
    ],
  },
  {
    title: "Athlete management",
    tools: [
      {
        name: "athlete_invite",
        summary: "Invite an athlete to your org",
      },
      {
        name: "athlete_archive",
        summary: "Archive an athlete",
      },
      {
        name: "athlete_restore",
        summary: "Restore an archived athlete",
      },
      {
        name: "athlete_saved_workouts",
        summary: "Saved workouts for an athlete",
      },
      {
        name: "log_athlete_set",
        summary: "Log a set for an athlete",
      },
      {
        name: "coach_log_session",
        summary: "Log a full session for an athlete",
      },
      {
        name: "swap_athlete_exercise",
        summary: "Swap an exercise in a session",
      },
      {
        name: "prescribe_athlete_set",
        summary: "Override prescribed sets",
      },
    ],
  },
  {
    title: "Teams & codes",
    tools: [
      {
        name: "team_create",
        summary: "Create a team",
      },
      {
        name: "team_update",
        summary: "Rename or update a team",
      },
      {
        name: "team_delete",
        summary: "Delete a team",
      },
      {
        name: "team_code_create",
        summary: "Create a join code",
      },
      {
        name: "team_code_delete",
        summary: "Delete a join code",
      },
      {
        name: "list_team_codes",
        summary: "Join codes for a team",
      },
    ],
  },
  {
    title: "Messaging & analytics",
    tools: [
      {
        name: "messaging_conversations",
        summary: "Message streams and teams",
      },
      {
        name: "messaging_read",
        summary: "Read a conversation",
      },
      {
        name: "message_draft",
        summary: "Draft a message",
      },
      {
        name: "message_send",
        summary: "Send a message",
      },
      {
        name: "message_delete",
        summary: "Delete a message",
      },
      {
        name: "analytics_query",
        summary: "Query readiness, volume, and more",
      },
      {
        name: "athlete_main_lift_prs",
        summary: "Main-lift PRs for one athlete",
      },
      {
        name: "roster_main_lift_prs",
        summary: "Main-lift PRs across the roster",
      },
    ],
  },
];

export const ATHLETE_TOOL_GROUPS: McpToolGroup[] = [
  {
    title: "Profile & history",
    tools: [
      {
        name: "athlete_whoami",
        summary: "Your athlete profile",
      },
      {
        name: "athlete_profile",
        summary: "Training profile summary",
      },
      {
        name: "athlete_prefs",
        summary: "Notification and display prefs",
      },
      {
        name: "athlete_working_maxes",
        summary: "Working maxes by lift",
      },
      {
        name: "athlete_leaderboard",
        summary: "Leaderboard standings",
      },
      {
        name: "athlete_workouts",
        summary: "Upcoming and recent workouts",
      },
      {
        name: "athlete_exercises",
        summary: "Search your exercise history",
      },
      {
        name: "athlete_exercise_history",
        summary: "History for one exercise",
      },
      {
        name: "athlete_personal_records",
        summary: "PRs for one exercise",
      },
      {
        name: "athlete_exercise_stats",
        summary: "Stats for one exercise",
      },
      {
        name: "athlete_log_targets",
        summary: "What to log today",
      },
    ],
  },
  {
    title: "Logging",
    tools: [
      {
        name: "athlete_session_create",
        summary: "Create a training session",
      },
      {
        name: "athlete_session_add_exercises",
        summary: "Add exercises to a session",
      },
      {
        name: "athlete_session_remove",
        summary: "Remove a session",
      },
      {
        name: "athlete_log_session",
        summary: "Log a full session",
      },
      {
        name: "athlete_log_set",
        summary: "Log one set",
      },
    ],
  },
];

export const HOSTED_ONLY_TOOLS: McpTool[] = [
  {
    name: "report_feedback",
    summary: "Report a bug or send feedback to the maintainers",
  },
  {
    name: "programming_sync",
    summary: "Sync prescribed programming history into D1",
  },
  {
    name: "programming_stored",
    summary: "Query synced programming history",
  },
  {
    name: "messaging_sync",
    summary: "Sync message history into D1",
  },
  {
    name: "messaging_stored",
    summary: "Query synced message history",
  },
  {
    name: "athlete_workouts_sync",
    summary: "Sync workout history into D1",
  },
  {
    name: "athlete_workouts_stored",
    summary: "Query synced workout history",
  },
  {
    name: "athlete_training_sync",
    summary: "Sync exercise history and PRs into D1",
  },
  {
    name: "athlete_training_stored",
    summary: "Query synced exercise history and PRs",
  },
];
